ca1/urls.py
import django.contrib.auth.views as auth_views

from sshkbase.forms import UserPasswordResetForm

"""ca1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sshkbase.urls')),

    path('admin/', admin.site.urls),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='registration/password-reset.html',
        form_class=UserPasswordResetForm), name='password_reset'),
    path('password-reset/sent', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password-reset-confirm.html'), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),

]

django-ca/urls.py
import django.contrib.auth.views as auth_views

from sshkbase.forms import UserPasswordResetForm

"""django-ca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sshkbase.urls')),

    path('admin/', admin.site.urls),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='registration/password-reset.html',
        form_class=UserPasswordResetForm), name='password_reset'),
    path('password-reset/sent', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password-reset-confirm.html'), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),

]

sshkbase/urls.py
from django.urls import path, include, reverse

from . import views

sidebar_links = [
    [
        ('sshkbase:index', "Home page"),
        ('sshkbase:user-detail', "Profile", lambda r: (r.user.nickname,)),
        ('sshkbase:user-update', "Change account info."),
        ('sshkbase:user-keys', "SSH Keys")
    ]
]

admin_sidebar_links = [
    ('admin:index', "Django administration")
]

app_name = "sshkbase"
urlpatterns = [
    # Here we list urls that are valid.
    # Each url is tied to a function sending back a response for the browser,
    # containing the HTML and CSS files to display
    # The 'name' attribute is used in html files to get the associated url
    path('', views.indexView, name='index'),
    path('users', views.listView, name='list'),
    path('users/<str:userNickname>', views.userDetailView, name='user-detail'),
    path('update-user', views.userUpdateView, name='user-update'),
    path('update-user/send', views.updateUser, name='user-update-send'),
    path('update-user/password', views.passwordUpdateView, name='user-update-password'),
    path('update-user/password/send', views.updatePassword, name='user-update-password-send'),
    path('delete-user', views.userDeleteView, name='user-delete'),
    path('delete-user/send', views.deleteUser, name='user-delete-send'),
    path('new-user', views.userAddView, name='user-new'),
    path('new-user/send', views.addUser, name='user-new-send'),
    path('login', views.userLoginView, name='user-login'),
    path('login/send', views.loginUser, name='user-login-send'),
    path('logout', views.logoutUser, name='user-logout'),

    path('new-key', views.keyAddView, name='add-key'),
    path('new-key/send', views.addKey, name='key-send'),
    path('keys', views.userKeysView, name='user-keys'),
    path('keys/<int:keyId>', views.keyDetailView, name='key-detail'),
    path('keys/<int:keyId>/send', views.updateKey, name='key-update'),
    path('keys/<int:keyId>/delete', views.keyDeleteView, name='key-delete'),
    path('keys/<int:keyId>/delete/send', views.deleteKey, name='key-delete-send'),
]

sshkbase/forms.py
from django.contrib.auth.forms import PasswordResetForm
from django import forms


class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'user-box',
        'placeholder': 'example@gaming.mlg',
        'type': 'email',
        'name': 'email'
    }))

sshkbase/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from . import urls
from .models import User, SSHKey

PERMISSION_NAMES = ['read', 'write']
PERMISSION_LABELS = {'read': 'Read', 'write': 'Write'}


# Other / utility functions
def isNicknameValid(nickname):
    if len(nickname) == 0 or str.isspace(nickname):
        return False

    validList = [c for c in "abcdefghijklmnopqrstuvwxyz0123456789-_"]
    for c in nickname:
        if c not in validList:
            return False
    return True


def isNicknameUnique(nickname):
    for u in User.objects.all():
        if nickname == u.nickname:
            return False
    return True


def boldifyCurrentPath(request, path, name):
    if request.path == str(path):
        return "<u>" + name + "</u>"
    return name


def reverseUrl(request, tup):
    if len(tup) == 3:
        return reverse(tup[0], args=tup[2](request))
    return reverse(tup[0])


def fillDetailContext(request, ctx: dict):
    """Adds links for detail pages in the given template context.`"""
    links = []
    for g in urls.sidebar_links:
        group = []
        for e in g:
            link = reverseUrl(request, e)
            group.append((link, boldifyCurrentPath(request, link, e[1])))
        links.append(group)
    ctx['links'] = links

    if request.user.isAdmin:
        admin_links = []
        for e in urls.admin_sidebar_links:
            link = reverseUrl(request, e)
            admin_links.append((link, boldifyCurrentPath(request, link, e[1])))

        ctx['admin_links'] = admin_links


# === BASIC VIEW FUNCTIONS ===

# Each one of these functions returns a HttpResponse containing the HTML and CSS
# to be displayed by the browser
# Functions ending with 'View' just get the values to be used inside the HTML templates,
# and render their respective template.

def indexView(request):
    # ???
    user = request.user
    if user is None or not user.is_authenticated:
        return render(request, 'sshkbase/index-anonymous.html', {})

    ctx = {
        'user': user,
    }
    fillDetailContext(request, ctx)
    return render(request, 'sshkbase/index.html', ctx)


def listView(request):
    userList = User.objects.order_by('nickname')
    ctx = {
        'userList': userList
    }
    return render(request, 'sshkbase/list.html', ctx)


def userAddView(request):
    return render(request, 'sshkbase/userInfo/userAdd.html', {})


def userLoginView(request):
    return render(request, 'sshkbase/userInfo/userLogin.html', {})


def userDetailView(request, userNickname):
    user = get_object_or_404(User, pk=userNickname)
    ctx = {
        'user': user,
        'self': request.user
    }
    fillDetailContext(request, ctx)
    return render(request, 'sshkbase/userInfo/userDetail.html', ctx)


def userUpdateView(request):
    user = request.user
    if user is None or not user.is_authenticated:
        return render(request, 'sshkbase/index-anonymous.html', {})
    ctx = {
        'user': user,
    }
    fillDetailContext(request, ctx)
    return render(request, 'sshkbase/userInfo/userUpdate.html', ctx)


def userKeysView(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))

    keys = SSHKey.objects.filter(user__nickname=user.nickname)
    ctx = {
        'user': user,
        'keys': keys
    }
    fillDetailContext(request, ctx)
    return render(request, 'sshkbase/userInfo/userKeys.html', ctx)


def userDeleteView(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))
    ctx = {
        'user': user
    }
    return render(request, 'sshkbase/userInfo/userDelete.html', ctx)


def passwordUpdateView(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))
    ctx = {
        'user': user
    }
    fillDetailContext(request, ctx)
    return render(request, 'registration/password-change.html', ctx)


def keyAddView(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))
    ctx = {
        'user': user,
    }
    fillDetailContext(request, ctx)
    return render(request, 'sshkbase/keyInfo/keyAdd.html', ctx)


# View details about a key
def keyDetailView(request, keyId):
    sshkey = get_object_or_404(SSHKey, pk=keyId)
    permInt = sshkey.permissions
    perms = dict()

    for n in PERMISSION_NAMES:
        perms[n] = bool(permInt & 1)
        permInt >>= 1
    ctx = {
        'sshkey': sshkey,
        'perms': perms,
        'perm_labels': PERMISSION_LABELS
    }
    fillDetailContext(request, ctx)

    return render(request, 'sshkbase/keyInfo/keyDetail.html', ctx)


def keyDeleteView(request, keyId):
    sshkey = get_object_or_404(SSHKey, pk=keyId)
    ctx = {
        'sshkey': sshkey
    }
    return render(request, 'sshkbase/keyInfo/keyDelete.html', ctx)


# === POST REQUEST HANDLERS ===

# Functions like this one are used when the browser sends a POST request containing information.
# The browsers send a POST request when it is necessary to send data to the server (and change some things
# in the database)
# This function adds a new user in the database
def addUser(request):
    # We gather the information sent with the request
    nickname = request.POST['nickname']
    full_name = request.POST['full-name']
    email = request.POST['email']
    password = request.POST['password']
    # Perform some checks to see if the given data is correct
    if not isNicknameValid(nickname):
        # If not, send a HTTP response to display whatever page we want (in this case the same page),
        # but with an error message attached
        return render(request, 'sshkbase/userInfo/userAdd.html', {
            'nickname_try': nickname,
            'name_try': full_name,
            'email_try': email,
            'error_msg': "Your nickname may only contain lowercase letters, digits, dashes and underscores."
        })

    if not isNicknameUnique(nickname):
        return render(request, 'sshkbase/userInfo/userAdd.html', {
            'nickname_try': nickname,
            'name_try': full_name,
            'email_try': email,
            'error_msg': "This nickname is already used."
        })

    # Create the object to be stored in the DB, give it all its values and save it
    user = User.objects.create_user(nickname=nickname, name=full_name, email=email, password=password)
    try:
        validate_password(password, user)
    except ValidationError as err:
        user.delete()
        return render(request, 'sshkbase/userInfo/userAdd.html', {
            'nickname_try': nickname,
            'name_try': full_name,
            'email_try': email,
            'error_msg': "Your password is invalid :",
            'passwd_errors': err.error_list
        })

    print("Added user " + user.nickname)
    # Finally send a HTTP response to redirect the user to a different page
    return HttpResponseRedirect(reverse('sshkbase:index'))


def loginUser(request):
    nickname = request.POST['nickname']
    rawPassword = request.POST['password']

    user = authenticate(request, nickname=nickname, password=rawPassword)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse('sshkbase:index'))
    else:
        return render(request, 'sshkbase/userInfo/userLogin.html', {
            'nickname_try': nickname,
            'error_msg': "Unknown password and/or username."
        })


def logoutUser(request):
    logout(request)
    return HttpResponseRedirect(reverse('sshkbase:index'))


def updateUser(request):
    # For update functions like this one, we get the existing object with the nickname we got from the URL,
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))

    newName = request.POST['name']
    # Change its name
    user.name = newName
    # And save it again to update the database
    user.save()
    print("Updated user " + user.nickname)
    # Then send a redirect response to redirect the user to the user detail page
    return HttpResponseRedirect(reverse('sshkbase:user-detail', args=(user.nickname,)))


# For deletion, we only need to get the object in the database, call the 'delete()' function.
# then redirect to the previous index page
def deleteUser(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))

    print("Deleted user " + user.nickname)
    user.delete()
    return HttpResponseRedirect(reverse('sshkbase:index'))


def updatePassword(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('sshkbase:index'))

    password = request.POST['password']
    password2 = request.POST['password-confirm']

    if password != password2:
        ctx = {
            'error_msg': "The two passwords are different",
        }
        fillDetailContext(request, ctx)
        return render(request, 'registration/password-change.html', ctx)

    try:
        validate_password(password, user)
    except ValidationError as err:
        ctx = {
            'error_msg': "The new password is invalid :",
            'passwd_errors': err.error_list
        }
        fillDetailContext(request, ctx)
        return render(request, 'registration/password-change.html', ctx)

    user.set_password(password)
    user.save()
    return HttpResponseRedirect(reverse('sshkbase:index'))


# Functions for keys do basically the same thing as user ones, but on keys.

templates/sshkbase/keyInfo/keyAdd.html
{% extends "detail.html" %}

{% block title %}Add a new ssh key{% endblock %}
{% block stylesheets %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'sshkbase/list-style.css' %}">
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'sshkbase/key-detail.css' %}">
{% endblock %}

{% block specific-headline %}
    <h2><a href="{% url 'sshkbase:user-keys' %}">SSH Keys</a>/New</h2>
{% endblock %}

{% block content %}
    {% if error_msg %}
        <h2 style="color: red;">Error: {{ error_msg }}</h2>
    {% endif %}

    <form action="{% url 'sshkbase:key-send' %}" method="post">
        {% csrf_token %}
        <dl class="form-group">
            <dt>
                <label for="key-title-box">Title</label>
            </dt>
            <dd>
                <input id="key-title-box" name="title" class="form-box" type="text">
            </dd>
        </dl>
        <dl class="form-group">
            <dt>
                <label for="key-box">Key</label>
            </dt>
            <dd>
                <textarea id="key-box" name="key" class="form-box"
                          placeholder='SSH public key, begins with "ssh-rsa", "ssh-ed25519"'></textarea>

            </dd>
        </dl>
        <dl class="form-group">
            <dt>Permissions</dt>
            <dd>
                <input id="key-perm-read" name="perm-read" type="checkbox">
                <label class="checkbox-label" for="key-perm-read">Read</label>
                <input id="key-perm-write" name="perm-write" type="checkbox">
                <label class="checkbox-label" for="key-perm-write">Write</label>
            </dd>
            <dd style="margin-top: 15px">
                <button class="add-button boxed-button">
                    <p>Add key</p>
                    <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                         class="h-6 w-6"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M 12 2 L 12 22 M 2 12 L 22 12" stroke-linejoin="round"
                              stroke-linecap="round"></path>
                    </svg>

                </button>
            </dd>
        </dl>
    </form>

{% endblock %}

templates/sshkbase/keyInfo/keyDelete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'sshkbase/base.css' %}">
    <link rel="stylesheet" href="{% static 'sshkbase/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'sshkbase/center-box.css' %}">
    <link rel="stylesheet" href="{% static 'sshkbase/key-delete.css' %}">
</head>
<body>

<header>
    <a href="{% url 'sshkbase:key-detail' sshkey.id %}" class="button-link">
        <button class="slide-button slide-reverse-button" style="--hovered-color: #f0f0f0">
            <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                 class="h-6 w-6"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M9 5l-7 7m0 0l7 7m-7-7H20" stroke-linejoin="round"
                      stroke-linecap="round"></path>
            </svg>
            <p id="back-to-key-detail-button-p">Back to key detail page</p>
        </button>
    </a>
</header>

<div class="login-box">

    <form action="{% url 'sshkbase:key-detail' sshkey.id %}" method="get">
        {% csrf_token %}
        <h2>Are you sure you want to delete SSH key "{{ sshkey.title }}" ?</h2>
        <h4>This cannot be undone.</h4>

        <div style="text-align: center;">
            <a href="{% url 'sshkbase:key-detail' sshkey.id %}" class="button-link">
                <button id="cancel-button" class="boxed-button" type="button">
                    <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                         class="h-6 w-6"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M9 5l-7 7m0 0l7 7m-7-7H20" stroke-linejoin="round"
                              stroke-linecap="round"></path>
                    </svg>
                    No, take me back !
                </button>
            </a>
            <button id="confirm-button" class="boxed-button"
                    formaction="{% url 'sshkbase:key-delete-send' sshkey.id %}"
                    formmethod="post">
                Yes, delete this key...
            </button>
        </div>
    </form>
</div>

</body>
</html>

templates/sshkbase/keyInfo/keyDetail.html
{% extends "detail.html" %}
{% block title %}Modify SSH key{% endblock %}

{% block stylesheets %}
    {% load static %}
    <!--This is used to tell Django to load our custom template filters-->
    <!--See 'sshkbase/filters.py' and 'ca/settings.py'-->
    {% load template_filters %}

    <link rel="stylesheet" href="{% static 'sshkbase/list-style.css' %}">
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'sshkbase/key-detail.css' %}">
{% endblock %}

{% block specific-headline %}
    <h2><a href="{% url 'sshkbase:user-keys' %}">SSH Keys</a>/{{ sshkey.title }}</h2>
{% endblock %}

{% block content %}
    {% if error_msg %}
        <h2 style="color: red;">Error: {{ error_msg }}</h2>
    {% endif %}
    <form action="{% url 'sshkbase:key-update' sshkey.id %}" method="post">
        {% csrf_token %}
        <dl class="form-group">
            <dt>
                <label for="key-title-box">Title</label>
            </dt>
            <dd>
                <input id="key-title-box" name="title" class="form-box" type="text" value="{{ sshkey.title }}">
            </dd>
        </dl>
        <dl class="form-group">
            <dt>
                <label for="key-box">Key</label>
            </dt>
            <dd>
                    <textarea id="key-box" name="key" class="form-box"
                              placeholder='SSH public key, begins with "ssh-rsa", "ssh-ed25519"'
                    >{{ sshkey.key }}</textarea>
            </dd>
        </dl>
        <dl class="form-group">
            <dt>Permissions</dt>
            <dd>
                {% for k, v in perms.items %}
                    <input id="key-perm-{{ k }}" name="perm-{{ k }}" type="checkbox"
                           {% if v %}checked="checked" {% endif %}>
                    <label class="checkbox-label" for="key-perm-{{ k }}">{{ perm_labels|get_item:k }}</label>
                {% endfor %}
            </dd>

        </dl>
        <div class="buttons" style="margin-top: 15px;">
            <button id="save-changes-button" class="boxed-button add-button">
                <p>Save changes</p>
                <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                     class="h-6 w-6"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M 12 2 L 12 22 M 2 12 L 22 12" stroke-linejoin="round"
                          stroke-linecap="round"></path>
                </svg>

            </button>

            <button class="boxed-button del-button" style="--hovered-color: #fb4934"
                    formaction="{% url 'sshkbase:key-delete' sshkey.id %}">
                <p>Delete</p>
                <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                     class="h-6 w-6"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M 4 4 L 20 20 M 4 20 L 20 4" stroke-linejoin="round"
                          stroke-linecap="round"></path>
                </svg>

            </button>
        </div>
    </form>
{% endblock %}