ca1/urls.py
import django.contrib.auth.views as auth_views

from sshkbase.forms import UserPasswordResetForm

"""ca1 URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sshkbase.urls')),

    path('admin/', admin.site.urls),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='registration/password-reset.html',
        form_class=UserPasswordResetForm), name='password_reset'),
    path('password-reset/sent', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password-reset-confirm.html'), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),

]

django-ca/urls.py
import django.contrib.auth.views as auth_views

from sshkbase.forms import UserPasswordResetForm

"""django-ca URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('sshkbase.urls')),

    path('admin/', admin.site.urls),
    path('password-reset', auth_views.PasswordResetView.as_view(
        template_name='registration/password-reset.html',
        form_class=UserPasswordResetForm), name='password_reset'),
    path('password-reset/sent', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password-reset-sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password-reset-confirm.html'), name='password_reset_confirm'),
    path('reset/complete', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password-reset-complete.html'), name='password_reset_complete'),

]

sshkbase/urls.py
from django.urls import path, include, reverse

from . import views

sidebar_links = [
    [
        ('sshkbase:index', "Home page"),
        ('sshkbase:user-detail', "Profile", lambda r: (r.user.nickname,)),
        ('sshkbase:user-update', "Change account info."),
        ('sshkbase:user-keys', "SSH Keys")
    ]
]

admin_sidebar_links = [
    ('admin:index', "Django administration")
]

app_name = "sshkbase"
urlpatterns = [
    # Here we list urls that are valid.
    # Each url is tied to a function sending back a response for the browser,
    # containing the HTML and CSS files to display
    # The 'name' attribute is used in html files to get the associated url
    path('', views.indexView, name='index'),
    path('users', views.listView, name='list'),
    path('users/<str:userNickname>', views.userDetailView, name='user-detail'),
    path('update-user', views.userUpdateView, name='user-update'),
    path('update-user/send', views.updateUser, name='user-update-send'),
    path('update-user/password', views.passwordUpdateView, name='user-update-password'),
    path('update-user/password/send', views.updatePassword, name='user-update-password-send'),
    path('delete-user', views.userDeleteView, name='user-delete'),
    path('delete-user/send', views.deleteUser, name='user-delete-send'),
    path('new-user', views.userAddView, name='user-new'),
    path('new-user/send', views.addUser, name='user-new-send'),
    path('login', views.userLoginView, name='user-login'),
    path('login/send', views.loginUser, name='user-login-send'),
    path('logout', views.logoutUser, name='user-logout'),

    path('new-key', views.keyAddView, name='add-key'),
    path('new-key/send', views.addKey, name='key-send'),
    path('keys', views.userKeysView, name='user-keys'),
    path('keys/<int:keyId>', views.keyDetailView, name='key-detail'),
    path('keys/<int:keyId>/send', views.updateKey, name='key-update'),
    path('keys/<int:keyId>/delete', views.keyDeleteView, name='key-delete'),
    path('keys/<int:keyId>/delete/send', views.deleteKey, name='key-delete-send'),
]

templates/center-box.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    {% load static %}
{% block stylesheets %}
    <link rel="stylesheet" href="{% static 'sshkbase/base.css' %}">
    <link rel="stylesheet" href="{% static 'sshkbase/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'sshkbase/center-box.css' %}">
{% endblock %}
</head>
<body>

<header>
    {% block header %}
        <a href="{% url 'sshkbase:index' %}" class="button-link">
            <button class="slide-button slide-reverse-button" style="--hovered-color: #f0f0f0">
                <svg stroke-width="4" stroke="currentColor" id="back-to-home-button" viewBox="0 0 24 24" fill="none"
                     class="h-6 w-6"
                     xmlns="http://www.w3.org/2000/svg">
                    <path d="M9 5l-7 7m0 0l7 7m-7-7H20" stroke-linejoin="round"
                          stroke-linecap="round"></path>
                </svg>
                <p>Back to home page</p>
            </button>
        </a>
    {% endblock %}
</header>

<div class="login-box">
    {% block content %}
        Center box template
    {% endblock %}
</div>

</body>
</html>

templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sample title{% endblock %}</title>
    {% load static %}
    {% block stylesheets %}
        <link rel="stylesheet" href="{% static 'sshkbase/base.css' %}">
        <link rel="stylesheet" href="{% static 'sshkbase/buttons.css' %}">
        <link rel="stylesheet" href="{% static 'sshkbase/detail-style.css' %}">
    {% endblock %}
</head>
<body>

<header style="min-height: 35px">
    {% block header %}
    <a href="{% url 'sshkbase:list' %}" class="button-link">
        <button class="slide-button slide-reverse-button" style="--hovered-color: #f0f0f0" id="list-users-button">
            <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none"
                 class="h-6 w-6"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M9 5l-7 7m0 0l7 7m-7-7H20" stroke-linejoin="round"
                      stroke-linecap="round"></path>
            </svg>
            <p>See other users</p>
        </button>
    </a>
    <a href="{% url 'sshkbase:user-logout' %}" class="button-link">
        <button class="slide-button" id="logout-button" style="--hovered-color: #f0f0f0">
            <p>Log out</p>
            <svg stroke-width="4" stroke="currentColor" viewBox="0 0 24 24" fill="none" class="h-6 w-6"
                 xmlns="http://www.w3.org/2000/svg">
                <path d="M14 5l7 7m0 0l-7 7m7-7H3" stroke-linejoin="round"
                      stroke-linecap="round"></path>
            </svg>

        </button>
    </a>
    {% endblock %}
</header>
<main>
    <div class="headline">
        {% block headline %}
            <h1>{{ user.name }}</h1>
            <h3>@{{ user.nickname }}</h3>
        {% endblock %}
    </div>
    <div class="flexbox-container">

        <div class="sidebar">
            {% block sidebar %}
                <ul>
                    {% for link_group in links %}
                        {% for l, n in link_group %}
                            <li>
                                <a href="{{ l }}" class="sidebar-link">{{ n|safe }}</a>
                            </li>

                        {% endfor %}
                        <hr class="solid">
                    {% endfor %}
                    {% if admin_links %}
                        {% for l,n in admin_links %}
                            <li>
                                <a href="{{ l }}" class="sidebar-link">{{ n|safe }}</a>
                            </li>
                        {% endfor %}
                    {% endif %}
                </ul>
            {% endblock %}
        </div>
        <div class="content-container">
            <div class="headline">
                {% block specific-headline %}
                    <h2>Welcome @{{ user.name }} !</h2>
                {% endblock %}
            </div>
            <hr class="solid">
            {% block content %}
                Sample content
            {% endblock %}
        </div>
    </div>
</main>

</body>
</html>